    var options = {
        auth_header : 'E9NZuB6A91e2J03PKA2g7wx0629czel8',
        organization_ids: [
            "3HRhnUtmtXnT1UHQHClAcP"
        ],
        project_ids: [
            "3HRhnUtmtXnT1UHQHClAcP"
        ]
    }
   var datasnap = require('datasnap')(options);
   var event = [  
                {  
                    "event_type":"communication_delivered",
                    "organization_ids":[  
                       "3HRhnUtmtXnT1UHQHClAcP"
                    ],
                    "project_ids":[  
                       "3HRhnUtmtXnT1UHQHClAcP"
                    ],
                    "place":{  
                       "id":"placeid",
                       "name":"Mission District",
                       "tags":[  
                          "womens",
                          "golf",
                          "shoes"
                       ],
                       "address":{  
                          "address1":"103 west street",
                          "address2":"",
                          "city":"San Francisco",
                          "region":"CA",
                          "zip":94107,
                          "zip4":3422
                       },
                       "last_place":"placeid-3",
                       "geofences":[  
                          {  
                             "geofenceid":"geofenceid2"
                          },
                          {  
                             "geofenceid":"geofenceid2"
                          }
                       ],
                       "beacons":[  
                          {  
                             "beaconid":"beaconid1"
                          },
                          {  
                             "beaconid":"beaconid2"
                          }
                       ]
                    },
                    "geofence":{  
                       "identifier":"geofence2",
                       "name":"SF Gelen Park",
                       "visibility":"ORGANIZATION",
                       "dwell_time":600000,
                       "start_time":"2014-12-14T20:24:01.123000+00:00",
                       "last_update_time":"2014-12-14T20:24:01.123000+00:00",
                       "tags":[  
                          "womens",
                          "golf",
                          "shoes"
                       ],
                       "geofence_circle":{  
                          "radius":100,
                          "coordinates":[  
                             -88.21337,
                             40.11041
                          ]
                       },
                       "geofence_polygon":{  
                          "locations":[  
                             {  
                                "coordinates":[  
                                   32.8953153522896,
                                   -117.19559844351653
                                ]
                             },
                             {  
                                "coordinates":[  
                                   32.8954009341414,
                                   -117.19516929007415
                                ]
                             },
                             {  
                                "coordinates":[  
                                   32.89564867061472,
                                   -117.1949815354431
                                ]
                             },
                             {  
                                "coordinates":[  
                                   32.89545949009762,
                                   -117.19463284827117
                                ]
                             },
                             {  
                                "coordinates":[  
                                   32.894986537037255,
                                   -117.19496544218902
                                ]
                             },
                             {  
                                "coordinates":[  
                                   32.894864920127866,
                                   -117.19554479933623
                                ]
                             }
                          ]
                       }
                    },
                    "global_position":{  
                       "location":{  
                          "coordinates":[  
                             -88.21337,
                             40.11041
                          ]
                       },
                       "altitude":13.00,
                       "accuracy":10,
                       "course":77.34375,
                       "speed":4.0
                    },
                    "beacon":{  
                       "vendor_identifier":"SHDG-28AHD",
                       "vendor":"gimbal",
                       "identifier":"SHDG-28AHD",
                       "ble_uuid":"ble_uuid",
                       "ble_vendor_uuid":"ble_vendor_uuid",
                       "ble_vendor_id":"ble_vendor_id",
                       "rssi":80,
                       "previous_rssi":70,
                       "name":"Front Entrance",
                       "dwell_time":600000,
                       "is_mobile":false,
                       "start_time":"2014-12-14T20:24:01.123000+00:00",
                       "coordinates":[  
                          32.89545949009762,
                          -117.19463284827117
                       ],
                       "visibility":"Private",
                       "battery_level":"50",
                       "temperature":"68.32",
                       "hardware":"HardwaretypeoftheBeacon",
                       "categories":[  
                          {  
                             "Sports":{  

                             }
                          },
                          {  
                             "Womens":{  
                                "subcategories":[  
                                   "golfshirts",
                                   "dresses"
                                ]
                             }
                          },
                          {  
                             "Mens":{  

                             }
                          }
                       ],
                       "tags":[  
                          "womens",
                          "golf",
                          "shoes"
                       ]
                    },
                    "communication":{  
                       "description":"mydescription",
                       "tags":[  
                          "womens",
                          "golf",
                          "shoes"
                       ],
                       "id":"commid",
                       "status":"active",
                       "vendor":"airpush",
                       "vendor_identifier":"1234",
                       "name":"10% offPushnotification",
                       "type":{  
                          "id":"typeid",
                          "name":"PushNotificaion"
                       },
                       "content":{  
                          "text":"get10%off!",
                          "description":"get10%offifyougotothe",
                          "image":"http: //appl.com/image.gif",
                          "html":"<p>Hithere!!get10%offnow!!</p>",
                          "url":"http: //www.apple.com"
                       }
                    },
                    "user":{  
                       "tags":[  
                          "womens",
                          "golf",
                          "shoes"
                       ],
                       "id":{  
                          "mobile_device_bluetooth_identifier":"8c4e1f232810d11be96edf47674f5641296a76f5",
                          "mobile_device_ios_idfa":"1a847de9f24b18eee3fac634b833b7887b32dea3",
                          "mobile_device_ios_openidfa":"09238dd4",
                          "mobile_device_ios_idfv":"092344",
                          "mobile_device_ios_udid":"123",
                          "datasnap_uuid":"datasnap_uuid",
                          "datasnap_app_user_id":"3474284734",
                          "web_domain_userid":"",
                          "web_cookie":"foo",
                          "domain_sessionid":"fqr9fgwer8vb9",
                          "web_network_userid":"billybob",
                          "web_user_fingerprint":"web_user_fingerprint",
                          "web_analytics_company_z_cookie":"",
                          "global_distinct_id":"userid1234",
                          "global_user_ipaddress":"user_ipaddress",
                          "mobile_device_fingerprint":"2da076c7ad28740c0b2a9b7fa6077c4f",
                          "facebook_uid":"2234433",
                          "mobile_device_google_advertising_id":"googid",
                          "mobile_device_google_google_advertising_id_opt_in":"true",
                          "unknown":"unknownid",
                          "":""
                       },
                       "opt_in_location":true,
                       "opt_in_push_notifications":true,
                       "opt_in_vendor":true,
                       "audience":{  
                          "Education":[  
                             "College"
                          ],
                          "Age":[  
                             "18-24"
                          ],
                          "Ethnicity":[  
                             "Caucasian"
                          ],
                          "Kids":[  
                             "NoKids"
                          ],
                          "Gender":[  
                             "Male"
                          ],
                          "Interests":[  
                             "Gettingfromheretothere",
                             "Biking",
                             "Automotive",
                             "Automotive.Cars"
                          ],
                          "Income":[  
                             "$30-60k"
                          ]
                       },
                       "user_properties":{  
                          "user_type":"VIP",
                          "user_spend":"high",
                          "engagement_time":"Greaterthan30minutes"
                       }
                    },
                    "campaign":{  
                       "id":"campaignid",
                       "name":"camapign10%offshoes",
                       "vendor":"urbanairship",
                       "vendor_identifier":"1234",
                       "tags":[  
                          "womens",
                          "golf",
                          "shoes"
                       ],
                       "subcampaigns":[  
                          {  
                             "id":"campaignid",
                             "name":"camapign11%offshoesmles"
                          }
                       ],
                       "targeting_rules":{  
                          "id":"targetingid",
                          "rules":[  
                             {  
                                "id":"ruleid1",
                                "name":"retailandclothingruleforbackofstore",
                                "place_ids":[  
                                   "placeid1"
                                ],
                                "audience":{  
                                   "Education":[  
                                      "NoCollege",
                                      "College",
                                      "GradSchool"
                                   ],
                                   "Age":[  
                                      "18-24",
                                      "25-34",
                                      "35-44",
                                      "45-55",
                                      "55+"
                                   ],
                                   "Ethnicity":[  
                                      "Caucasian",
                                      "AfricanAmerican",
                                      "Asian",
                                      "Hispanic",
                                      "Other"
                                   ],
                                   "Kids":[  
                                      "NoKids",
                                      "HasKids"
                                   ],
                                   "Gender":[  
                                      "Male",
                                      "Female"
                                   ],
                                   "Interests":[  
                                      "Gettingfromheretothere",
                                      "Biking",
                                      "Automotive",
                                      "Automotive.Cars"
                                   ],
                                   "Income":[  
                                      "$0-30k",
                                      "$30-60k",
                                      "$60-100k",
                                      "100k+"
                                   ]
                                },
                                "targeting_attributes":{  
                                   "store_type":"retail",
                                   "product_type":"clothing"
                                }
                             },
                             {  
                                "id":"ruleid2",
                                "name":"mycoolrule2",
                                "audience":{  
                                   "Education":[  
                                      "NoCollege",
                                      "College",
                                      "GradSchool"
                                   ],
                                   "Age":[  
                                      "18-24",
                                      "25-34",
                                      "35-44",
                                      "45-55",
                                      "55+"
                                   ],
                                   "Ethnicity":[  
                                      "Caucasian",
                                      "AfricanAmerican",
                                      "Asian",
                                      "Hispanic",
                                      "Other"
                                   ],
                                   "Kids":[  
                                      "NoKids",
                                      "HasKids"
                                   ],
                                   "Gender":[  
                                      "Male",
                                      "Female"
                                   ],
                                   "Interests":[  
                                      "Gettingfromheretothere",
                                      "Biking",
                                      "Automotive",
                                      "Automotive.Cars"
                                   ],
                                   "Income":[  
                                      "$0-30k",
                                      "$30-60k",
                                      "$60-100k",
                                      "100k+"
                                   ]
                                }
                             }
                          ]
                       },
                       "time_filter":{  
                          "monday":{  
                             "start":"08: 00",
                             "end":"13: 00"
                          },
                          "tuesday":{  
                             "start":"08: 00",
                             "end":"22: 00"
                          }
                       },
                       "time_trigger":{  
                          "monday":"08: 00",
                          "tuesday":"13: 00"
                       },
                       "communication_ids":[  
                          "commid1",
                          "commid2"
                       ]
                    },
                    "datasnap":{  
                       "timestamp":"2014-12-14T20:24:01.123000+00:00",
                       "created":"2014-12-12T20:24:01.123000+00:00",
                       "txn_id":"fgfgbrrwvb",
                       "customer_txn_id":"fgfgbrrwvb",
                       "device":{  
                          "user_agent":"Mozilla/5.0 (Linux; U; Android 4.0.3; ko-kr; LG-L160L Build/IML74K) AppleWebkit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30",
                          "ip_address":"127.1.1.1",
                          "platform":"ios",
                          "os_version":"7.0",
                          "model":"iPhone5",
                          "manufacturer":"Apple",
                          "name":"hashed device name",
                          "vendor_id":"63A7355F-5AF2-4E20-BE55-C3E80D0305B1",
                          "carrier_name":"Verizon",
                          "country_code":"1",
                          "network_code":"327"
                       }
                    }
                 }
              ]
   datasnap.trackEvent(event);

